development:
  adapter: postgresql
  encoding: unicode
  database: baywing_dev
  pool: 5
  username: postgres
  password: Marzen95
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: baywing_test
  pool: 5
  username: postgres
  password: Marzen95
  host: localhost
  port: 5432